
platform :ios, '8.0'
xcodeproj 'FashionSocial.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'UIDevice-Hardware'
pod 'SVProgressHUD'
pod 'Parus'
pod 'StaticDataTableViewController'
pod 'SSKeychain'
pod 'AGEmojiKeyboard'
pod 'SDWebImage'
pod 'IDMPhotoBrowser'
pod 'MPGNotification'
pod 'Reachability'
pod 'AFNetworking'
pod 'MRProgress'
pod 'Toast'
pod 'SWRevealViewController'
pod 'DZNEmptyDataSet'
pod 'SWTableViewCell'
pod 'UIViewController+KeyboardAnimation'
pod 'NSDate+TimeAgo'
pod 'JSQMessagesViewController'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'